# Generated by Django 5.0 on 2023-12-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_students_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='gham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=255)),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
