# Generated by Django 5.0 on 2023-12-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_gham_delete_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gham',
        ),
    ]
