# Generated by Django 5.0 on 2023-12-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
    ]
