# Generated by Django 5.0 on 2024-01-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0009_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('national_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
