# Generated by Django 5.0 on 2024-01-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='national_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
