# Generated by Django 5.0 on 2024-01-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_customers_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='broadcasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('status', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('national_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customers')),
            ],
        ),
    ]
