# Generated by Django 5.0 on 2024-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_broadcasts'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('order_point', models.IntegerField()),
                ('status', models.BooleanField()),
                ('name', models.CharField(max_length=256)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
