# Generated by Django 5.0 on 2024-01-11 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1024)),
                ('national_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.customers')),
            ],
        ),
    ]
