# Generated by Django 5.0 on 2024-01-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('price_per_unit', models.FloatField()),
                ('total_price', models.FloatField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.products')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.projects')),
            ],
        ),
        migrations.AddConstraint(
            model_name='buy',
            constraint=models.UniqueConstraint(fields=('code', 'project_id', 'timestamp'), name='buy_table_primary_key'),
        ),
    ]
