# Generated by Django 5.0 on 2024-01-11 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_buy_buy_buy_table_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.projects', unique=True),
        ),
    ]
