# Generated by Django 5.0 on 2024-01-11 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_buy_project_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='buy',
            name='buy_table_primary_key',
        ),
        migrations.AlterField(
            model_name='buy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buy',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.projects'),
        ),
        migrations.AddConstraint(
            model_name='buy',
            constraint=models.UniqueConstraint(fields=('id', 'code', 'project_id', 'timestamp'), name='buy_table_primary_key'),
        ),
    ]
