# Generated by Django 5.0 on 2024-01-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_buy_buy_table_primary_key_alter_buy_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='buy',
            name='buy_table_primary_key',
        ),
    ]
