# Generated by Django 5.0 on 2024-01-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_buy_buy_table_primary_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='buy',
            constraint=models.UniqueConstraint(fields=('id', 'code', 'project_id', 'timestamp'), name='buy_table_primary_key'),
        ),
    ]
