# Generated by Django 5.0 on 2024-01-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_buy_project_id_alter_projects_national_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='amout',
            new_name='amount',
        ),
    ]
