# Generated by Django 5.0 on 2024-01-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_rename_amout_payments_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('price_per_unit', models.FloatField()),
            ],
        ),
    ]
