# Generated by Django 5.0 on 2024-01-11 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='works',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.projects')),
            ],
        ),
    ]
