# Generated by Django 5.0 on 2024-01-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_works'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='description',
        ),
    ]
