# Generated by Django 5.0 on 2024-01-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_remove_works_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.FloatField()),
                ('price_per_unit', models.FloatField()),
                ('total_price', models.FloatField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.services')),
                ('work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.works')),
            ],
        ),
    ]
