# Generated by Django 5.0 on 2024-01-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_work_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_report',
            old_name='code',
            new_name='service_code',
        ),
    ]
